name: CI (matrix over libs)
defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  push:
    branches:
    - main
  pull_request:
  workflow_run:
    workflows: [ "update_docker" ]
    types: [ completed ]
    branches: [ main ]

jobs:
  to-lowercase:
    runs-on: ubuntu-latest
    outputs:
      repo_lowercase: ${{ steps.lowercase.outputs.repository }}
    steps:
      - id: lowercase
        run: |
          echo "repository=ghcr.io/${GITHUB_REPOSITORY,,}:jazzy" >> $GITHUB_OUTPUT

  test_each_lib:
    needs: [to-lowercase]
    strategy:
      fail-fast: false
      matrix:
        include:
          - lib: giskardpy
          - lib: krrood
          - lib: semantic_digital_twin
          - lib: pycram
          - lib: random_events
          - lib: probabilistic_model
          - lib: multiverse_simulators
    uses: ./.github/workflows/ci_reusable.yml
    with:
      lib: ${{ matrix.lib }}
      repo_lowercase: ${{ needs.to-lowercase.outputs.repo_lowercase }}
