name: CI reusable
defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  workflow_call:
    inputs:
      lib:
        description: "Library folder name (relative to repo root)"
        required: true
        type: string
      repo_lowercase:
        description: "Lowercase repository name with tag"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.repo_lowercase }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: cognitive_robot_abstract_machine
          submodules: recursive

      - name: Initialize submodules explicitly
        run: |
          cd cognitive_robot_abstract_machine
          git config --global --add safe.directory "*"
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Install dependencies
        run: |
          cd cognitive_robot_abstract_machine
          source /opt/ros/cram-env/bin/activate
          poetry install

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: /github/home/.cache/semantic_digital_twin
          key: ${{ runner.os }}-cache-${{ inputs.lib }}-${{ github.ref_name }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cache-${{ inputs.lib }}-${{ github.ref_name }}
            ${{ runner.os }}-cache-${{ inputs.lib }}
            ${{ runner.os }}-cache-

      - name: List files in cache 1
        run: |
          ls -R /github/home/.cache/semantic_digital_twin

      - name: Build ORM
        if: ${{inputs.lib == 'pycram' || inputs.lib == 'semantic_digital_twin'}}
        run: |
          cd cognitive_robot_abstract_machine/${{ inputs.lib }}/scripts/
          source /opt/ros/overlay_ws/install/setup.bash
          source /opt/ros/cram-env/bin/activate
          python generate_orm.py

      - name: Run tests
        run: |
          source /opt/ros/overlay_ws/install/setup.bash
          source /opt/ros/cram-env/bin/activate
          python -m pytest -sv cognitive_robot_abstract_machine/test/${{ inputs.lib }}_test

      - name: Save cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: /github/home/.cache/semantic_digital_twin
          key: ${{ runner.os }}-cache-${{ inputs.lib }}-${{ github.ref_name }}-${{ github.run_id }}

      - name: List files in cache 2
        run: |
          ls -R /github/home/.cache/semantic_digital_twin
